name: Continuous integration

on: [pull_request, push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Create npm configuration
      run: echo "//npm.pkg.github.com/:_authToken=${token}" >> ~/.npmrc
      env:
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v1

    - name: "npm ci"
      run: npm ci

    - name: "npm run build"
      run: npm run build

    - name: "npm run test"
      run: npm run test
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run clippy-check action (expected pass)
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --manifest-path test_clippy/Cargo.toml -- -A clippy::approx_constant

    - name: Run clippy-check action (expected fail)
      continue-on-error: true
      id: clippy_fail
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --manifest-path test_clippy/Cargo.toml

    - name: Verify failure of previous step
      if: steps.clippy_fail.outcome != 'failure'
      run: echo "::error::Clippy passed when it should have failed" && exit 1
